import "server-only";

import { del, get, head, issueSignedToken, presignUrl, put } from "@vercel/blob";

import type { StorageAdapter, StorageEnv } from "./providers";

/**
 * Vercel Blob.
 *
 * The convenient option when the deployment is already on Vercel: no bucket to
 * create and no keys to rotate, just a store bound to the project.
 *
 * Written with `access: "private"`, which is the only setting compatible with
 * how this application treats files. Every read goes through /api/files/[id],
 * which checks the session and the organization before it serves a byte; a
 * public blob would still be readable by anyone holding the URL, and one
 * business's job photos are not something to protect with an unguessable
 * address alone.
 */

function token(env: StorageEnv) {
  const value = env.BLOB_READ_WRITE_TOKEN?.trim();
  if (!value) {
    throw new Error(
      "Storage is set to Vercel Blob, but BLOB_READ_WRITE_TOKEN is not set.\n" +
        "Vercel adds it automatically once a Blob store is connected to the project.",
    );
  }
  return value;
}

export function vercelBlobAdapter(env: StorageEnv = process.env): StorageAdapter {
  const readWriteToken = token(env);

  return {
    id: "vercel-blob",
    label: "Vercel Blob",

    async put(key, body, mimeType) {
      await put(key, Buffer.from(body), {
        access: "private",
        token: readWriteToken,
        contentType: mimeType,
        // The key already ends in a UUID generated by keys.ts. A second random
        // suffix here would change the pathname we just recorded in the
        // database, and the file would never be found again.
        addRandomSuffix: false,
      });
    },

    async get(key) {
      const result = await get(key, { access: "private", token: readWriteToken });
      if (!result || result.stream === null) return null;

      return Buffer.from(await new Response(result.stream).arrayBuffer());
    },

    async remove(key) {
      // Already-absent is not an error here, which matches the other adapters:
      // the database row is the record that matters.
      await del(key, { token: readWriteToken });
    },

    async presignUpload(key, mimeType, maxBytes) {
      const validUntil = Date.now() + PRESIGN_SECONDS * 1000;

      // Two steps, unlike S3: a delegation token scoped to this one pathname
      // and operation, then a URL signed under it. The scoping matters — the
      // token is what stops a presigned URL for one file being reused to write
      // anywhere else in the store.
      const signedToken = await issueSignedToken({
        token: readWriteToken,
        pathname: key,
        operations: ["put"],
        validUntil,
        allowedContentTypes: [mimeType],
        maximumSizeInBytes: maxBytes,
      });

      const { presignedUrl } = await presignUrl(signedToken, {
        operation: "put",
        access: "private",
        pathname: key,
        validUntil,
        allowedContentTypes: [mimeType],
        maximumSizeInBytes: maxBytes,
        addRandomSuffix: false,
      });

      return {
        url: presignedUrl,
        method: "PUT" as const,
        headers: { "Content-Type": mimeType },
        expiresAt: validUntil,
      };
    },

    async stat(key) {
      try {
        const result = await head(key, { token: readWriteToken });
        return { sizeBytes: result.size, mimeType: result.contentType ?? null };
      } catch {
        // head() throws BlobNotFoundError rather than returning null.
        return null;
      }
    },
  };
}

/** Matches the S3 adapter: long enough for a slow phone, short enough to expire. */
const PRESIGN_SECONDS = 10 * 60;
